package finguard.model;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Immutable fraud alert generated by the risk engine.
 */
public class FraudAlert {

    public enum Severity { SAFE, SUSPICIOUS, HIGH_RISK, FRAUD_ALERT }

    private final String        accountId;
    private final int           riskScore;
    private final Severity      severity;
    private final String        reason;
    private final LocalDateTime detectedAt;

    // Component scores
    private final int highValueCount;
    private final int cityChanges;
    private final int deviceSwitches;
    private final double totalSpending;

    public FraudAlert(String accountId, int riskScore, Severity severity, String reason,
                      int highValueCount, int cityChanges, int deviceSwitches, double totalSpending) {
        this.accountId      = accountId;
        this.riskScore      = riskScore;
        this.severity       = severity;
        this.reason         = reason;
        this.detectedAt     = LocalDateTime.now();
        this.highValueCount = highValueCount;
        this.cityChanges    = cityChanges;
        this.deviceSwitches = deviceSwitches;
        this.totalSpending  = totalSpending;
    }

    public String        getAccountId()      { return accountId; }
    public int           getRiskScore()      { return riskScore; }
    public Severity      getSeverity()       { return severity; }
    public String        getReason()         { return reason; }
    public LocalDateTime getDetectedAt()     { return detectedAt; }
    public int           getHighValueCount() { return highValueCount; }
    public int           getCityChanges()    { return cityChanges; }
    public int           getDeviceSwitches() { return deviceSwitches; }
    public double        getTotalSpending()  { return totalSpending; }

    public static Severity scoreToSeverity(int score) {
        if (score <= 15)  return Severity.SAFE;
        if (score <= 30)  return Severity.SUSPICIOUS;
        if (score <= 50)  return Severity.HIGH_RISK;
        return Severity.FRAUD_ALERT;
    }

    @Override
    public String toString() {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return String.format(
            "[%s]\n  Account  : %s\n  Score    : %d\n  Severity : %s\n  Reason   : %s\n" +
            "  Details  : HighVal=%d  CityChg=%d  DevSwitch=%d  Spending=₹%.2f",
            detectedAt.format(fmt), accountId, riskScore, severity, reason,
            highValueCount, cityChanges, deviceSwitches, totalSpending);
    }

    /** File-friendly formatted string */
    public String toFileRecord() {
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return String.format(
            "=== %s ===\nAccount: %s | Score: %d | Severity: %s\nReason: %s\n" +
            "HighValue=%d | CityChanges=%d | DeviceSwitches=%d | TotalSpend=%.2f\n",
            detectedAt.format(fmt), accountId, riskScore, severity, reason,
            highValueCount, cityChanges, deviceSwitches, totalSpending);
    }
}
